export const terminology = {
  Koran: "Quraan",
  Quran: "Quraan",
  QurAn: "Quraan",
  Hadith: "Hadiith",
  Hadithe: "Hadiithe",
  Zakat: "Zakaah",
  Zakah: "Zakaah",
  Almosen: "Zakaah",
  Almosengabe: "Zakaah",
  Almosensteuer: "Zakaah",
  Vers: "Aayah",
  Verse: "Aayaat",
  Kapitel: "Suurah",
  Scharia: "Scharii'ah",
  Schariah: "Scharii'ah",
  "islamisches Recht": "Scharii'ah",
  "islamisches Gesetz": "Scharii'ah",
  Rechtsgutachten: "Fatwa",
  Rechtsschule: "Fiqh-Schule",
  Gebet: "Salaah",
  Fasten: "Siyaam",
  Glauben: "Iimaan",
  Gläubiger: "Mu'min",
  Ungläubiger: "Kaafir",
  Glaubensbekenntnis: "Schahaadah",
  Bittgebet: "Du'aa",
  Moschee: "Masdschid",
};